Songshukr\MainBundle\Entity\Commodity:
    type: entity
    table: commodity
    id:
        cid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 16384
            fixed: false
            comment: ''
        logo:
            type: string
            nullable: true
            length: 256
            fixed: false
            comment: ''
        oprice:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        unit:
            type: string
            nullable: true
            length: 16
            fixed: false
            comment: ''
            default: '0'
        status:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        allowance:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        utime:
            type: datetime
            nullable: true
            comment: ''
        ctime:
            type: datetime
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
