Songshukr\MainBundle\Entity\Label:
    type: entity
    table: label
    id:
        lid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        value:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: ''
        ctime:
            type: datetime
            nullable: true
            comment: ''
        utime:
            type: datetime
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
