Songshukr\MainBundle\Entity\Order:
    type: entity
    table: order
    id:
        oid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orderNo:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
            default: ''
            column: order_no
        cid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        number:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            default: '0'
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ctime:
            type: datetime
            nullable: true
            comment: ''
        utime:
            type: datetime
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
