Songshukr\MainBundle\Entity\Orders:
    type: entity
    table: orders
    id:
        oid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        orderNo:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
            default: ''
            column: order_no
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        ctime:
            type: datetime
            nullable: true
            comment: ''
        utime:
            type: datetime
            nullable: true
            comment: ''
        name:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: ''
        cellphone:
            type: string
            nullable: true
            length: 16
            fixed: false
            comment: ''
        address:
            type: string
            nullable: true
            length: 1024
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
