Songshukr\MainBundle\Entity\User:
    type: entity
    table: user
    id:
        uid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        cellphone:
            type: string
            nullable: true
            length: 16
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 128
            fixed: false
            comment: ''
        address:
            type: string
            nullable: true
            length: 1024
            fixed: false
            comment: ''
        ctime:
            type: datetime
            nullable: true
            comment: ''
        utime:
            type: datetime
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
